// isHelloWorld requirements


/**
 * The isHelloWorld method determines if a String equals 'Hello World'.
 * (1) Given the String 'Hello World', the method returns "Yes, it Is."
 * (2) Given some other String, the method returns 'No, it is not!'.
 * (3) Given a null or empty string, the method returns 'No, it is not!'.
 */

// A HelloWorld stub class


public class NewHelloWorld {
  public static String isHelloWorld(String myString) {
    return null;
  }
}